### ISSUE TITLE
Room heating example is broken on Stratego 8.8, works well on Stratego 8.7

### ISSUE THREAD

**Issue by mihsamusev** [mihsamusev/stratego_mpc_example#8]
Seems like a regex problem because no output from `verifyta`
```
Traceback (most recent call last):
  File "RoomHeating_online_control.py", line 67, in <module>
    controller.run(period, horizon, duration)
  File "/home/trafiklab/anaconda3/envs/stratego_mpc_pip/lib/python3.8/site-packages/strategoutil.py", line 278, in run
    new_value = extract_state(result, var, controlperiod)
  File "/home/trafiklab/anaconda3/envs/stratego_mpc_pip/lib/python3.8/site-packages/strategoutil.py", line 34, in extract_state
    float_tuples = get_float_tuples(result.group())
AttributeError: 'NoneType' object has no attribute 'group'
```
Running verifyta separately gives
```
EXCEPTION: The __RESET__ annotation has been deprecated (Location: Monitor), please use the {..} -> {..} learning annotation instead.
```

**Comment by magoorden** [comment]
Where did you get version 8.8? The latest one I have is 8.7.
